name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: echo "RELEASE_TITLE=$(date +'v%Y.%m.%d')" >> $GITHUB_ENV

      - name: Build Image
        run: docker build -f build/Dockerfile -t ponces/treble .

      - name: Get Keys
        uses: actions/checkout@v4
        with:
          repository: ponces/vendor_ponces-priv
          token: ${{ secrets.GH_TOKEN }}
          path: vendor_ponces-priv

      - name: Build ROM
        run: |
          mkdir builds
          docker run --rm \
                     --privileged \
                     --name treble \
                     --volume ${{ github.workspace }}/builds:/root/builds \
                     --volume ${{ github.workspace }}/vendor_ponces-priv:/aosp/vendor/ponces-priv \
                     --volume ${{ github.workspace }}/config/ota.json:/aosp/treble_aosp/config/ota.json \
                     ponces/treble treblebuild

      - name: Upload OTA
        uses: actions/upload-artifact@v4
        with:
          name: ota
          path: config/ota.json

      - name: Upload ROM
        uses: softprops/action-gh-release@v1
        with:
          files: builds/*.xz
          title: ${{ env.RELEASE_TITLE }}
          tag_name: ${{ env.RELEASE_TITLE }}
          body: "## Changelog\n- ...\n\n## Notes\n- ..."
          draft: true
          prerelease: false
